#!/usr/bin/env python3
"""App icon: three tiles (red circle, blue square, yellow triangle) passing
through a turnstile bar on a deep teal ground. Writes the 1024 asset and a
512/64 PNG pair for the worker's landing page.
    python tools/make_icon.py
"""
import base64
import os

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
S = 1024
img = Image.new("RGB", (S, S), (10, 74, 70))
d = ImageDraw.Draw(img)
# soft vertical gradient
for y in range(S):
    t = y / S
    d.line([(0, y), (S, y)], fill=(int(10 + 8 * t), int(74 + 28 * (1 - t)), int(70 + 30 * (1 - t))))

# turnstile bar (a horizontal gate with a hinge on the left)
bar_y = int(S * 0.56)
d.rounded_rectangle([int(S * 0.10), bar_y - 26, int(S * 0.90), bar_y + 26], radius=26, fill=(230, 236, 236))
d.ellipse([int(S * 0.06), bar_y - 60, int(S * 0.06) + 120, bar_y + 60], fill=(230, 236, 236))
d.ellipse([int(S * 0.06) + 40, bar_y - 20, int(S * 0.06) + 80, bar_y + 20], fill=(10, 74, 70))

# tiles above the bar
tile = int(S * 0.19)
gap = int(S * 0.05)
x0 = (S - (3 * tile + 2 * gap)) // 2
y0 = int(S * 0.20)
RED, BLUE, YELLOW = (220, 38, 38), (37, 99, 235), (242, 184, 13)
for k, colour in enumerate((RED, BLUE, YELLOW)):
    x = x0 + k * (tile + gap)
    d.rounded_rectangle([x, y0, x + tile, y0 + tile], radius=int(tile * 0.22), fill=(255, 255, 255, 40) if False else (24, 108, 102))
    pad = int(tile * 0.18)
    box = [x + pad, y0 + pad, x + tile - pad, y0 + tile - pad]
    if k == 0:
        d.ellipse(box, fill=colour)
    elif k == 1:
        d.rounded_rectangle(box, radius=int(tile * 0.08), fill=colour)
    else:
        d.polygon([((box[0] + box[2]) // 2, box[1]), (box[2], box[3]), (box[0], box[3])], fill=colour)

# accept tick below the bar, subtle
cx, cy = int(S * 0.5), int(S * 0.78)
d.line([(cx - 90, cy), (cx - 25, cy + 60), (cx + 110, cy - 70)], fill=(45, 212, 191), width=44, joint="curve")

out = os.path.join(ROOT, "Turnstile", "Assets.xcassets", "AppIcon.appiconset", "AppIcon1024.png")
img.save(out, "PNG")
print("wrote", out)

# Worker copies (base64 TS module).
def b64(size):
    im = img.resize((size, size), Image.LANCZOS)
    p = os.path.join(ROOT, "worker", "fixtures", f"icon_{size}.png")
    im.save(p, "PNG", optimize=True)
    return base64.b64encode(open(p, "rb").read()).decode()

ts = f'// Generated by tools/make_icon.py\nexport const ICON_512_B64 = "{b64(512)}";\nexport const ICON_64_B64 = "{b64(64)}";\n'
ts += 'export function pngBytes(b64: string): Uint8Array { const s = atob(b64); const out = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i); return out; }\n'
with open(os.path.join(ROOT, "worker", "src", "icon.ts"), "w", encoding="utf-8") as fh:
    fh.write(ts)
print("wrote worker/src/icon.ts")
